In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"/messy_sales_dataset.csv")

In [21]:
df.head()

,invoice_id,order_date,customer_name,customer_email,country,city,product_name,category,quantity,unit_price,discount,payment_method,sales_rep,region,status,shipping_cost,tax,total_amount,currency
0,INV-1090,2019-09-04,Matthew Alvarez,NaN,Germany,West Timothy,Office Chair,Furniture,1,79.96,0.0,Bank Transfer,NaN,North America,completed,15.0,-15.19,-67.35,TND
1,INV-1049,1995-05-28,Gary Heath,NaN,Spain,Amandabury,Printer HP 2024,Electronics,2,961.71,150.0,credit card,NaN,Europe,completed,NaN,365.45,-961.71,TND
2,INV-1050,NaT,Roy Gray,yrocha@example.net,Tunisia,Wendyview,Laptop Pro 15,Electronics,1,431.18,15.0,Bank Transfer,NaN,North America,Completed,15.0,-81.92,-366.50,EUR
3,INV-1049,1985-05-04,Mrs. Kari Andrews,raymondmckee@example.org,Spain,North Jamesview,USB-C Cable,Accessories,0,397.98,0.0,Credit Card,Holly,Africa,completed,NaN,0.00,0.00,EUR
4,INV-1083,NaT,Linda Wells,NaN,Tunisia,West Jamie,Printer HP 2024,Electronics,1,958.76,0.0,PayPal,NaN,Africa,Completed,5.0,182.16,958.76,USD

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      2000 non-null   object
 1   order_date      1493 non-null   object
 2   customer_name   2000 non-null   object
 3   customer_email  1341 non-null   object
 4   country         2000 non-null   object
 5   city            2000 non-null   object
 6   product_name    2000 non-null   object
 7   category        2000 non-null   object
 8   quantity        2000 non-null   int64
 9   unit_price      2000 non-null   float64
 10  discount        1651 non-null   float64
 11  payment_method  2000 non-null   object
 12  sales_rep       1010 non-null   object
 13  region          2000 non-null   object
 14  status          2000 non-null   object
 15  shipping_cost   1513 non-null   float64
 16  tax             2000 non-null   float64
 17  total_amount    2000 non-null   float64
 18  currency        2000 non-null   object
dtypes: float64(5), int64(1), object(13)
memory usage: 297.0+ KB

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isna().sum()

invoice_id          0
order_date        507
customer_name       0
customer_email    659
country             0
city                0
product_name        0
category            0
quantity            0
unit_price          0
discount          349
payment_method      0
sales_rep         990
region              0
status              0
shipping_cost     487
tax                 0
total_amount        0
currency            0
dtype: int64

In [7]:
df.shape

(2000, 19)

In [9]:
df['order_date']=pd.to_datetime(df['order_date'],format='mixed')

In [10]:
df['country'].unique()

array(['Germany', 'Spain', 'tunisia', 'France', 'Tunisia', 'USA', 'Italy',
       'U.S.A'], dtype=object)

In [12]:

country_mapping = {
    'tunisia': 'Tunisia',
    'USA': 'United States',
    'U.S.A': 'United States'
}

df['country'] = df['country'].replace(country_mapping)


df['country'] = df['country'].str.title()


print(df['country'].unique())

['Germany' 'Spain' 'Tunisia' 'France' 'United States' 'Italy']

In [19]:
df['category'].value_counts()

category
Electronics    1212
Furniture       410
Accessories     189
Stationery      189
Name: count, dtype: int64

In [18]:
df['category'] = df['category'].str.title()

In [20]:
df['quantity']=df['quantity'].abs()

In [24]:
df['payment_method'].value_counts()

payment_method
Paypal           665
Credit Card      623
Bank Transfer    360
Cash             352
Name: count, dtype: int64

In [23]:
df['payment_method']=df['payment_method'].str.title()

In [25]:
df['tax']=df['tax'].abs()

In [27]:
df['currency'].value_counts()

currency
EUR    683
TND    681
USD    636
Name: count, dtype: int64

In [28]:
df['total_amount']=df['total_amount'].abs()

In [29]:
df['status'].unique()

array(['completed', 'Completed', 'Pending', 'complete', 'Cancelled'],
      dtype=object)

In [31]:
df['status'] = df['status'].str.title()

df['status'] = df['status'].replace({'Complete': 'Completed'})

In [32]:
df.isna().sum()

invoice_id          0
order_date        507
customer_name       0
customer_email    659
country             0
city                0
product_name        0
category            0
quantity            0
unit_price          0
discount          349
payment_method      0
sales_rep         990
region              0
status              0
shipping_cost     487
tax                 0
total_amount        0
currency            0
dtype: int64

In [33]:
df['sales_rep'] = df['sales_rep'].fillna('Unknown')
df['customer_email'] = df['customer_email'].fillna('Unknown')

In [34]:
df['discount'] = df['discount'].fillna(0.0)
df['shipping_cost'] = df['shipping_cost'].fillna(0.0)

In [35]:
df = df.dropna(subset=['order_date'])

In [36]:
df

,invoice_id,order_date,customer_name,customer_email,country,city,product_name,category,quantity,unit_price,discount,payment_method,sales_rep,region,status,shipping_cost,tax,total_amount,currency
0,INV-1090,2019-09-04,Matthew Alvarez,Unknown,Germany,West Timothy,Office Chair,Furniture,1,79.96,0.0,Bank Transfer,Unknown,North America,Completed,15.0,15.19,67.35,TND
1,INV-1049,1995-05-28,Gary Heath,Unknown,Spain,Amandabury,Printer HP 2024,Electronics,2,961.71,150.0,Credit Card,Unknown,Europe,Completed,0.0,365.45,961.71,TND
3,INV-1049,1985-05-04,Mrs. Kari Andrews,raymondmckee@example.org,Spain,North Jamesview,USB-C Cable,Accessories,0,397.98,0.0,Credit Card,Holly,Africa,Completed,0.0,0.00,0.00,EUR
5,INV-1062,2024-12-26,Alexandra Simon,Unknown,France,South Cindy,Standing Desk,Furniture,2,12.09,10.0,Paypal,Unknown,North America,Pending,15.0,4.59,21.76,EUR
7,INV-1071,1985-11-10,Amanda Colon,barnettmitchell@example.net,Tunisia,North Deborahshire,Keyboard Mechanical,Electronics,2,1477.14,0.0,Bank Transfer,George,Europe,Completed,0.0,561.31,2954.28,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,INV-1057,1984-04-27,Nicole Clark,ybaker@example.com,Tunisia,Port Alexandriastad,Tablet Air,Electronics,1,588.43,150.0,Paypal,Unknown,North America,Completed,0.0,111.80,294.21,EUR
1995,INV-1010,2003-04-18,Kyle Armstrong,bademail.com,Tunisia,Kendraton,Standing Desk,Furniture,5,1471.78,10.0,Paypal,Unknown,Africa,Pending,5.0,1398.19,6623.01,USD
1996,INV-1031,1998-06-09,Katrina Marshall,bademail.com,Spain,Mcgeeville,Standing Desk,Furniture,0,712.77,5.0,Credit Card,Unknown,Europe,Cancelled,15.0,0.00,0.00,USD
1998,INV-1005,2010-10-31,Rachel Sims,Unknown,Italy,East Gary,Laptop Pro 15,Electronics,5,17.39,150.0,Credit Card,Henry,Europe,Cancelled,5.0,16.52,43.48,EUR
1999,INV-1077,1997-07-23,Kelly Hernandez,bademail.com,Italy,South Jessicabury,Keyboard Mechanical,Electronics,1,536.92,0.0,Paypal,Claudia,North America,Completed,0.0,102.01,536.92,TND